version: "1"
services:
  ese-client1:
    image: saumyabhatt10642/ese-client:simulate
    env_file:
      - ./.env

  ese-client2:
    image: saumyabhatt10642/ese-client:simulate
    env_file:
      - ./.env

  ese-client3:
    image: saumyabhatt10642/ese-client:simulate
    env_file:
      - ./.env

  ese-client4:
    image: saumyabhatt10642/ese-client:simulate
    env_file:
      - ./.env
