version: '3'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    container_name: schema-registry
    hostname: schema-registry
    depends_on:
      - broker1
      - broker2
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://broker1:9092,PLAINTEXT://broker2:9092

  broker1:
    image: confluentinc/cp-kafka:latest
    container_name: broker1
    ports:
      - "19092:19092"
      - "19093:19093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: DOCKER_LISTENER://broker1:9092,LOCAL_LISTENER://broker1:19092,EXTERNAL_LISTENER://broker1:19093
      KAFKA_ADVERTISED_LISTENERS: DOCKER_LISTENER://broker1:9092,LOCAL_LISTENER://localhost:19092,EXTERNAL_LISTENER://${ESE_HOST_IP}:19093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_LISTENER:PLAINTEXT,LOCAL_LISTENER:PLAINTEXT,EXTERNAL_LISTENER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_LISTENER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: on-failure

  broker2:
    image: confluentinc/cp-kafka:latest
    container_name: broker2
    ports:
      - "29092:29092"
      - "29093:29093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: DOCKER_LISTENER://broker2:9092,LOCAL_LISTENER://broker2:29092,EXTERNAL_LISTENER://broker2:29093
      KAFKA_ADVERTISED_LISTENERS: DOCKER_LISTENER://broker2:9092,LOCAL_LISTENER://localhost:29092,EXTERNAL_LISTENER://${ESE_HOST_IP}:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_LISTENER:PLAINTEXT,LOCAL_LISTENER:PLAINTEXT,EXTERNAL_LISTENER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_LISTENER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: on-failure

  apigw:
    image: confluentinc/cp-kafka-rest:latest
    container_name: apigw
    ports:
      - "8082:8082"
    depends_on:
      - broker1
      - broker2
    environment:
      KAFKA_REST_BOOTSTRAP_SERVERS: PLAINTEXT://broker1:9092,PLAINTEXT://broker2:9092
      KAFKA_REST_LISTENERS: http://apigw:8082

  ui:
    container_name: ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8083:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true

  post-setup:
    build: ./setup
    container_name: post-setup
    depends_on:
      - broker1
      - broker2
      - schema-registry
    restart: "no"
